NewTISelvagem/NewTISelvagem.UI.Web/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewTISelvagem.Aplicacao;
using NewTISelvagem.Dominio;

namespace NewTISelvagem.UI.Web.Controllers
{
    public class AlunoController : Controller
    {
        //
        // GET: /Aluno/
        private readonly AlunoAplicacao appAluno;

        public AlunoController()
        {
            //appAluno = AlunoAplicacaoConstrutor.AlunoAplicacaoADO();//usando ADO
            appAluno = AlunoAplicacaoConstrutor.AlunoAplicacaoEF();//usa Entity Framework
        }

        public ActionResult Index()
        {
            var listarTodos = appAluno.ListaTodos();
            return View(listarTodos);
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Cadastrar(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                appAluno.Salvar(aluno);
                return RedirectToAction("Index");
            }
            return View(aluno);
        }

        public ActionResult Editar(string id)
        {
            var aluno = appAluno.ListaPorId(id);
            if (aluno == null)
                return HttpNotFound();

            return View(aluno);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(Aluno aluno)
        {
            if (ModelState.IsValid)
            {
                appAluno.Salvar(aluno);
                return RedirectToAction("Index");
            }
            return View(aluno);
        }

        public ActionResult Detalhes(string id)
        {
            var aluno = appAluno.ListaPorId(id);
            if (aluno == null)
                return HttpNotFound();

            return View(aluno);
        }

        public ActionResult Excluir(string id)
        {
            var aluno = appAluno.ListaPorId(id);
            if (aluno == null)
                return HttpNotFound();

            return View(aluno);
        }

        [HttpPost, ActionName("Excluir")]
        [ValidateAntiForgeryToken]
        public ActionResult ExcluirConfirmar(string id)
        {
            var aluno = appAluno.ListaPorId(id);
            appAluno.Deletar(aluno);
            return RedirectToAction("Index");
        }
    }
}

NewTISelvagem/NewTISelvagem.UI.Web/Controllers/HomeController.cs
using NewTISelvagem.Aplicacao;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewTISelvagem.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult Index()
        {
            return View();
        }

    }
}

NewTISelvagem/NewTISelvagem.UI.Web/Views/Aluno/Cadastrar.cshtml
@model NewTISelvagem.Dominio.Aluno

@{
    ViewBag.Title = "Cadastrar";
}

<h2>Cadastrar</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Aluno</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Mae)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Mae)
            @Html.ValidationMessageFor(model => model.Mae)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataNascimento)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DataNascimento)
            @Html.ValidationMessageFor(model => model.DataNascimento)
        </div>

        <p>
            <input type="submit" value="Cadastrar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewTISelvagem/NewTISelvagem.UI.Web/Views/Aluno/Detalhes.cshtml
@model NewTISelvagem.Dominio.Aluno

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<fieldset>
    <legend>Aluno</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mae)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mae)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DataNascimento)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DataNascimento)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Editar", "Editar", new { id=Model.AlunoId }) |
    @Html.ActionLink("Voltar", "Index")
</p>

NewTISelvagem/NewTISelvagem.UI.Web/Views/Aluno/Editar.cshtml
@model NewTISelvagem.Dominio.Aluno

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Aluno</legend>

        @Html.HiddenFor(model => model.AlunoId)

        <div class="editor-label">
            @Html.LabelFor(model => model.Nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Nome)
            @Html.ValidationMessageFor(model => model.Nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Mae)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Mae)
            @Html.ValidationMessageFor(model => model.Mae)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DataNascimento)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DataNascimento)
            @Html.ValidationMessageFor(model => model.DataNascimento)
        </div>

        <p>
            <input type="submit" value="Salvar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewTISelvagem/NewTISelvagem.UI.Web/Views/Aluno/Excluir.cshtml
@model NewTISelvagem.Dominio.Aluno

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Deseja excluir esse registro?</h3>
<fieldset>
    <legend>Aluno</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Nome)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Nome)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Mae)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Mae)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DataNascimento)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DataNascimento)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Excluir" /> |
        @Html.ActionLink("Cancelar", "Index")
    </p>
}

NewTISelvagem/NewTISelvagem.UI.Web/Views/Aluno/Index.cshtml
@model IEnumerable<NewTISelvagem.Dominio.Aluno>

@{
    ViewBag.Title = "Listagem";
}

<h2>Lista de Alunos</h2>

<p>
    @Html.ActionLink("Novo Aluno", "Cadastrar")
</p>
<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Mae)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataNascimento)
        </th>
        <th>
            Opções
        </th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Mae)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.AlunoId }) |
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.AlunoId }) |
                @Html.ActionLink("Excluir", "Excluir", new { id = item.AlunoId })
            </td>
        </tr>
    }
</table>

NewTISelvagem/NewTISelvagem.UI.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Inicial";
}

<h2>Página Inicial</h2>

NewTISelvagem/NewTISelvagem.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div>
        @Html.ActionLink("Home", "Index", "Home")
        @Html.ActionLink("Cadastro de Aluno", "Index", "Aluno")
    </div>
    @RenderBody()

    @Scripts.Render("~/bundles/jquery")
    @RenderSection("scripts", required: false)
</body>
</html>