NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Models/ClienteModel.cs
using NewPizarriaSys.Dominio;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace NewPizarriaSys.UI.Web.Models
{
    public class ClienteModel
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage=" * Campo Obrigatório.")]
        public string Nome { get; set; }

        [Required(ErrorMessage=" * Campo Obrigatório.")]
        //[RegularExpression(@"^[A-Za-z0-9]*\d+[A-Za-z0-9]*$", ErrorMessage="Somente números.")]
        public string Telefone { get; set; }

        [Required(ErrorMessage=" * Campo Obrigatório.")]
        public string Email { get; set; }

        public ClienteModel()
        {

        }

        public ClienteModel(Cliente cliente)
        {
            Id = cliente.Id;
            Nome = cliente.Nome;
            Telefone = cliente.Telefone;
            Email = cliente.Email;
        }
    }
}

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Controllers/ClienteController.cs
using NewPizarriaSys.Dominio.Negocios;
using NewPizarriaSys.Dominio.Contrato;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using NewPizarriaSys.UI.Web.Models;
using NewPizarriaSys.Dominio;

namespace NewPizarriaSys.UI.Web.Controllers
{
    public class ClienteController : Controller
    {
        private readonly IClienteNegocio _clienteNegocio = new ClienteNegocio();

        public ActionResult Index(ClienteModel model)
        {
            if (ModelState.IsValid)
            {
                var cliFone = _clienteNegocio.ListarTelefones(model.Telefone);
                return View(cliFone);
            }

            var cliente = _clienteNegocio.ListarTodos();
            return View(cliente);
        }

        [HttpGet]
        public ActionResult Inserir()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Inserir(ClienteModel model)
        {
            if (ModelState.IsValid)
            {
                _clienteNegocio.Salvar(new Cliente
                {
                    Nome = model.Nome,
                    Telefone = model.Telefone,
                    Email = model.Email
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Editar(int id)
        {
            var cliente = _clienteNegocio.BuscarPorId(id);
            return View(new ClienteModel(cliente));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar(ClienteModel model)
        {
            if (ModelState.IsValid)
            {
                _clienteNegocio.Salvar(new Cliente
                {
                    Id = model.Id,
                    Nome = model.Nome,
                    Telefone = model.Telefone,
                    Email = model.Email
                });
                return RedirectToAction("Index");
            }
            return View(model);
        }

        [HttpGet]
        public ActionResult Detalhes(int id)
        {
            var cliente = _clienteNegocio.BuscarPorId(id);
            return View(new ClienteModel(cliente));
        }

        [HttpGet]
        public ActionResult Excluir(int id)
        {
            var cliente = _clienteNegocio.BuscarPorId(id);
            return View(new ClienteModel(cliente));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Excluir(ClienteModel model)
        {
            _clienteNegocio.Excluir(new Cliente { Id = model.Id });
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Consultar()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Consultar(string telefone)
        {
            var cliente = _clienteNegocio.ListarTelefones(telefone);
            if (cliente.Count() == 0)
                return View();

            return View("Index", cliente);
        }
    }
}

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NewPizarriaSys.UI.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Somos especializados em Pizzas desde 2017.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Contate-nos para sua festa ou para domicílio.";

            return View();
        }
    }
}

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Cliente/Consultar.cshtml
@{
    ViewBag.Title = "Consultar";
}

<h2>Consultar</h2>

@using (Html.BeginForm())
{
    <div>
        <hr />
        <div class="form-group">
            @Html.Label("Digite o Telefone", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.Editor("telefone", new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <hr />
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Consultar" class="btn btn-default" />
            </div>
        </div>
    </div>
    <br />
    <p>
        @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
    </p>
}

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Cliente/Detalhes.cshtml
@model NewPizarriaSys.UI.Web.Models.ClienteModel

@{
    ViewBag.Title = "Detalhes";
}

<h2>Detalhes</h2>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.Id }, new { @class = "btn btn-default" })
    @Html.ActionLink("Excluir", "Excluir", new { id = Model.Id }, new { @class = "btn btn-default" })
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</p>

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Cliente/Editar.cshtml
@model NewPizarriaSys.UI.Web.Models.ClienteModel

@{
    ViewBag.Title = "Editar";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome)
                @Html.ValidationMessageFor(model => model.Nome)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone)
                @Html.ValidationMessageFor(model => model.Telefone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Cliente/Excluir.cshtml
@model NewPizarriaSys.UI.Web.Models.ClienteModel

@{
    ViewBag.Title = "Excluir";
}

<h2>Excluir</h2>

<h3>Deseja realmente excluir esse cliente?</h3>
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefone)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Excluir" class="btn btn-default" /> |
            @Html.ActionLink("Cancelar", "Index", null, new { @class = "btn btn-default" })
        </div>
    }
</div>

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Cliente/Index.cshtml
@model IEnumerable<NewPizarriaSys.Dominio.Cliente>

    @{
        ViewBag.Title = "Listagem";
    }

    <h2>Lista de Clientes</h2>

    <p>
        @Html.ActionLink("Novo", "Inserir", null, new { @class = "btn btn-default" })
        @Html.ActionLink("Consultar", "Consultar", null, new { @class = "btn btn-default" })
    </p>

    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Telefone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                Opcões
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Telefone)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.ActionLink("Editar", "Editar", new { id = item.Id }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Detalhes", "Detalhes", new { id = item.Id }, new { @class = "btn btn-default" })
                    @Html.ActionLink("Excluir", "Excluir", new { id = item.Id }, new { @class = "btn btn-default" })
                </td>
            </tr>
        }

    </table>

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Cliente/Inserir.cshtml
@model NewPizarriaSys.UI.Web.Models.ClienteModel

@{
    ViewBag.Title = "Cadastro";
}

<h2>Cadastro de Cliente</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Cliente</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome)
                @Html.ValidationMessageFor(model => model.Nome)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefone, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefone)
                @Html.ValidationMessageFor(model => model.Telefone)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email)
                @Html.ValidationMessageFor(model => model.Email)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Salvar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index", null, new { @class = "btn btn-default" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Home/About.cshtml
@{
    ViewBag.Title = "Sobre";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Somos especializados em Pizzas desde 2017.</p>

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contato";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    PizzariaSys<br />
    Av. Dionisio Leonel Alencar<br />
    <abbr title="Fone">Telefone</abbr>
    +55 85 98862-9450
</address>

<address>
    <strong>Suporte:</strong>   <a href="mailto:support@pizzariasys.com">support@pizzariasys.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:marketing@pizzaria.com">marketing@pizzaria.com</a>
</address>

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Início";
}

<div class="jumbotron">
    <h1>PizzariaSys</h1>
    <p class="lead">PizzariaSys is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="http://asp.net" class="btn btn-primary btn-large">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            PizzariaSys MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="http://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NewPizarriaSys/NewPizarriaSys/NewPizarriaSys.UI.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PizzariaSys</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("PizzariaSys", "Index", "Home", null, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Início", "Index", "Home")</li>
                    @*Cria um menu*@
                    <li role="presentation" class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                            Clientes <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu" role="menu">
                            <li>@Html.ActionLink("Listagem", "Index", "Cliente")</li>
                            <li>@Html.ActionLink("Cadastrar", "Inserir", "Cliente")</li>
                            <li>@Html.ActionLink("Consultar", "Consultar", "Cliente")</li>
                        </ul>
                    </li>
                    <li>@Html.ActionLink("Sobre", "About", "Home")</li>
                    <li>@Html.ActionLink("Contato", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                Data: @DateTime.Now.Day/@DateTime.Now.Month/@DateTime.Now.Year 
                Hora: @DateTime.Now.Hour:@DateTime.Now.Minute <br /> &copy; PizzariaSys
        </p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>